export const Images = {
  ZARA_LOGO: require("./Logo.png"),
  ZARA_LOGO_LIGHT: require('./Zara-Light-Logo.png'),
  LINES: require("./LINES.png"),
  GRAIN: require("./Grain-Background.png"),
  DRESS_1: require("./Dress-1.jpeg"),
  DRESS_2: require("./Dress-2.jpeg"),
  DRESS_3: require("./Dress-3.jpeg"),
  MODEL_1: require("./Model-1.png"),
  MODEL_2: require("./Model-2.png"),
  MODEL_3: require("./Model-3.png"),
  WOMEN_CATALOG_1: require('./Women-Catalog1.jpeg'),
  WOMEN_CATALOG_2: require('./Women-Catalog2.jpeg'),
  WOMEN_CATALOG_3: require('./Women-Catalog3.jpeg'),
  WOMEN_CATALOG_4: require('./Women-Catalog4.jpeg'),
  WOMEN_CATALOG_5: require('./Women-Catalog5.jpg'),
  WOMEN_CATALOG_6: require('./Women-Catalog6.jpeg'),
  WOMEN_CATALOG_7: require('./Women-Catalog7.jpg'),
  WOMEN_CATALOG_8: require('./Women-Catalog8.jpg'),
  WOMEN_CATALOG_9: require('./Women-Catalog9.jpg'),
  FOOTER_IMAGE: require('./Footer-Background.png'),
  CATALOG_IMAGE_1: require('./Catalog-Image1.jpeg'),
  CATALOG_IMAGE_2: require('./Catalog-Image2.jpeg'),
  CATALOG_IMAGE_3: require('./Catalog-Image3.jpeg'),
  CATALOG_IMAGE_4: require('./Catalog-Image4.jpeg'),
  MATCH_IMAGE_1: require('./Match-Image1.jpeg'),
  MATCH_IMAGE_2: require('./Match-Image2.jpeg'),
};
